name: CI Tests
on: push

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyversions:
          - '3.9.1'
    steps:
      - name: Clone source
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversions }}
          architecture: 'x64'
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Install dependencies and test
        run: |
          poetry install
          poetry run python -m pytest tests/ -vv